name: Auto Deploy Backend to VPS

on:
  push:
    branches:
      - DEV  # ganti sesuai branch deploy kamu

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 28101
          timeout: 60s
          script: |
            cd /opt/chain_fit_be

            # Ambil kode terbaru
            git pull origin DEV
            git status
            git remote -v
            git branch -vv

            # Build ulang image Docker
            docker build --no-cache -t test_journaling_humic .

            # Stop & remove container lama kalau ada
            docker stop test_journaling_humic-server || true
            docker rm test_journaling_humic-server || true
            # Run container baru dengan env & expose port
            docker run -d \
              --name test_journaling_humic-server \
              --network db-network \
              -p 4001:4001 \
              -e DATABASE_URL="mysql://root:rootpass@mysql-container-a:3306/mood_journal_app" \
              -e EMAIL_USERNAME="${{ secrets.EMAIL_USERNAME }}" \
              -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e FE_URL="${{secrets.FE_URL}}" \
              -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
              --restart unless-stopped \
              -e BE_URL="${{ secrets.BE_URL }}" \
              test_journaling_humic
            docker exec -i test_journaling_humic-server npx prisma migrate deploy
            docker exec -i test_journaling_humic-server npx prisma db seed