name: Auto Deploy Backend to VPS

on:
  push:
    branches:
      - dev  # ganti sesuai branch deploy kamu
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 28101
          timeout: 60s
          script: |
            cd /opt/chain_fit_be

            # Ambil kode terbaru
            
            git pull origin dev
            git status
            git remote -v
            git branch -vv

            # Build ulang image Docker
            docker build --no-cache -t chain_fit_be .

            # Stop & remove container lama kalau ada
            docker stop chain_fit_be-server || true
            docker rm chain_fit_be-server || true
            # Run container baru dengan env & expose port
            docker run -d \
              --name chain_fit_be-server \
              --network db-network \
              -p 4002:4002 \
              -e DATABASE_URL="mysql://root:rootpass@mysql-container-a:3306/gym_be" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e IS3_ACCESS_KEY_ID="${{ secrets.IS3_ACCESS_KEY_ID }}" \
              -e IS3_BUCKET_NAME="${{ secrets.IS3_BUCKET_NAME }}" \
              -e IS3_END_POINT="${{ secrets.IS3_END_POINT }}" \
              -e IS3_PREFIX="${{ secrets.IS3_PREFIX }}" \
              -e IS3_REGION="${{ secrets.IS3_REGION }}" \
              -e IS3_SECRET_ACCESS_KEY_ID="${{ secrets.IS3_SECRET_ACCESS_KEY_ID }}" \
              -e MIDTRANS_CLIENT_KEY="${{ secrets.MIDTRANS_CLIENT_KEY }}" \
              -e MIDTRANS_IS_PRODUCTION="${{ secrets.MIDTRANS_IS_PRODUCTION }}" \
              -e MIDTRANS_SERVER_KEY="${{ secrets.MIDTRANS_SERVER_KEY }}" \
              -e URL_PATH_EQUIPMENT="${{ secrets.URL_PATH_EQUIPMENT }}" \
              -e FE_URL="${{secrets.FE_URL}}" \
              --restart unless-stopped \
              -e BE_URL="${{ secrets.BE_URL }}" \
              chain_fit_be
            docker exec -i chain_fit_be-server npx prisma migrate deploy
            docker exec -i chain_fit_be-server npx prisma db seed

